# ========================================================================
# Copyright 2026 Valerio Di Tommaso (@gyratina)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================
# project: Organic Gestures Modules (OGM)
# project-start: 2026-06-26 (yyyy-mm-dd)
# author-username: @gyratina (on GitHub)
# author-name: Valerio Di Tommaso
# author-email: contact.me@valerioditommaso.dev
# file-name: pyproject.toml
# ========================================================================
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ogm-vision"
version = "0.1.4"
authors = [
  { name="Valerio Di Tommaso", email="contact.me@valerioditommaso.dev" },
]
description = "API that allows the implementation of highly customizable hands and facial gestures."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
dependencies = [
    "mediapipe",
    "opencv-python",
    "numpy",
    "scipy"
]

[project.urls]
"Homepage" = "https://github.com/gyratina/Organic-Gestures-Modules"
"Repository" = "https://github.com/gyratina/Organic-Gestures-Modules"
"Bug Tracker" = "https://github.com/gyratina/Organic-Gestures-Modules/issues"

[tool.setuptools.packages.find]
include = ["ogm*"]

[tool.setuptools.package-data]
ogm = ["models/*.task"]
